### ISSUE TITLE
vars can't have hyphen in ansible

### ISSUE THREAD

**Issue by yanc0** [helldrum/anna_ansible_check#1]
If role has hyphen in its name, hyphen have to be changed into underscore when declaring variables.

`cat my-role/defaults/main.yml`
```yaml
my_role_foo: true
my_role_bar: false
```

issue here:
https://github.com/helldrum/ansible_check/blob/master/role_check.py#L151

**Comment by helldrum** [comment]
i add a control on the ansible_galaxy tags directly, now galaxy tags and variable prefix should match pattern [a-z0-1_]* to be considerate as a valid input.
it's prevent fancy galaxy tags as well.
please let me know if it's good for you :)

**Comment by QuentinDeSoete** [comment]
No that's not good because tags can have hyphens in ansible_galaxy tags.
for example we can have a role "go-carbon" and a role "carbon".
If we can have hyphens both roles would have tag carbon which can cause some issues.

**Comment by helldrum** [comment]
Hello, Thank for you feed back,
You can use undescore instead, filter autorize minus letters, number and undescore. So you can Have 2 galaxy tags one with go_carbon and carbon and go_carbon_3 if you want too :) can you please explain  Why should we have tag like go-carbon and prefix go_carbon ?
Thank
________________________________

**Comment by helldrum** [comment]
you can now use hyphen or underscore on galaxy tag, hyphen should be remplaced by underscore on variables prefix. 
ex: 
if galaxy tag = go-carbon  -> prefix should be go_carbon
if galaxy tag = go_carbon -> prefix should be go_carbon
